package com.exasol.adapter.dialects.trino.docgeneration;

import com.exasol.adapter.dialects.trino.TrinoSqlDialectFactory;
import com.exasol.autogeneratedresourceverifier.AutogeneratedResourceVerifier;

public class TrinoAutogeneratedResourceVerifier {
    public static void main(final String[] args) {
        new AutogeneratedResourceVerifier().verifyResource(new CapabilitiesReport(new TrinoSqlDialectFactory()));
    }
}
